### ISSUE TITLE
Why two demo projects in the library?

### ISSUE THREAD

**Issue by mohammedzamakhan** [filipesilva/angular-quickstart-lib#10]
I see two demo applications in the project, one src/demo, and another integration/src?

Whats the use case?

**Comment by filipesilva** [comment]
The demo application consumes the library in JIT mode and runs in watch mode so you can see your library in the browser while you work.

The integration app consumes the library in JIT and AOT mode and runs e2e tests so that you can verify that the built package works correctly when installed via npm. This is important to test the packaging step.

**Comment by mohammedzamakhan** [comment]
Can't this be done by just using one?

**Comment by filipesilva** [comment]
The only way to test the integration fully works is by repackaging, so if you were trying to develop on watch mode the rebuild would take far longer than it does on the demo (which doesn't repackage).
