### ISSUE TITLE
Images and other assets

### ISSUE THREAD

**Issue by danwulff** [filipesilva/angular-quickstart-lib#9]
Can you give some guidance as to how to include other assets within a library? I'm specifically thinking about .pngs, .svgs etc. For instance, I have a header component that I'd like to have an image within. Of course, there's the option of using a data URI but I'd like to be able to include raw files within the lib.

Can you think of what would make the most sense for including raw assets and using them within library components? Do you know of any libraries that already exist that have a logical way of including assets? Is including raw images in a library a dumb idea? Any help would be great.

Thanks for the quickstart lib, it's been great help getting started creating a library for our dev team.

**Comment by loixlab** [comment]
I added this line in the "// Copy package files" block
```
.then(() => _relativeCopy('./assets/**/*.*', rootFolder, distFolder))
```

to copy my assets folder to the dist folder
My assets folder is sibling with the src folder, like so:

```
/src
    /lib
/assets
```

**Comment by filipesilva** [comment]
I don't think there's any definite answer currently regarding library assets. The best example I can think of is https://github.com/angular/material2, that provides separate theme css and also suggests loading icons.

Some build systems (like the one in Angular CLI) support loading image and font assets from CSS, but different preprocessors (scss/less/stylus) might do it differently and it's not really fair to impose that library users use a certain preprocessor.

There's also general assets that your library might need. This is where it gets tough because it implies interaction with the build system beyond the well defined module systems of JS/CSS. Configuring runtime (in the browser) loading of files is not as easy as it sounds, and if you've ever fiddled with SystemJS configuration this will be obvious.

I think the most straightforward way is to provide some files (like the assets in @sebelga's comment) that you tell users they have to copy over to their distribution root. This might sound very manual and low tech, but that's really a good thing. That means the consumer is in control, and whatever custom configuration they use in their host will probably work.

Another option is to inline, but that isn't possible for all assets and will drastically increase JS payload.

You can also provide configurable asset reference, like a component input that specifies an image url and has a default. 

I don't have foolproof guidance on this topic though. These are merely discussion points.

**Comment by loixlab** [comment]
True that I didn't mention my use case.
I am building a package "specially" for Angular cli which allows to load assets from node_modules assets when needed

https://stackoverflow.com/questions/41555624/how-to-include-assets-from-node-modules-in-angular-cli-project

So it is not a one size fit all but I like @filipesilva I think that our job is to make the assets available and let the user use them how the need them.

By the was, thanks @filipesilva for this great lib starter, you saved me to much time! 👍

**Comment by danwulff** [comment]
Thanks for the reply, all that makes sense. I'll be copying over some .css files to distribute, a few very small images I'll inline as Base64 encoded. Otherwise I'll include URLs to our internal CDN for large images (few and far between)
